### PR TITLE
Add 'defaultWait' timeout setting

### LINKED ISSUE #13: Replace the `immediately` flag?
I'm not sure the "immediately" flag actually does anything... ??  @christian-bromann has told me (if I understood correctly) that all webdriverio methods that look for elements (`isVisible`, `getText`, etc) will implicitly `waitForExist` until the default timeout expires.  So there's no way to implement a functional `immediately` flag, as I understand it.

We *could* however implement an `eventually` flag that would add some timeout, or maybe even take a timeout as a parameter, and wait for the specified amount of time. (which would follow a recommended practice of setting your default timeout to 0, and waiting as necessary).

Or we could just remove it altogether, and if you need to wait, you can do it explicitly before firing a test :)

### PR DESCRIPTION
**Pull request by mltsy**
Closes #13 

This also makes a couple breaking changes, so look over those (see CHANGELOG.md) and let me know what you think!

### CODE REVIEW

**Comment by marcodejongh** [comment]
Thx for the PR!

**Comment by mltsy** [comment]
Woohoo! :+1:  My pleasure.  Looking forward to using the new features :smile:

**Comment by marcodejongh** [comment]
@mltsy published in 0.4.0

**Comment by mltsy** [comment]
Yay! :tada: ... Oh, maybe you meant it *will be* published in 0.4.0 - looks like 0.4.0 isn't available via npm yet?

**Comment by marcodejongh** [comment]
@mltsy I did try to publish it but I fired a yarn publish and forgot, checked this morning and it was still publishing... Anyway should be published now (with npm publish this time)

**Comment by mltsy** [comment]
Oooh, hah strange!  Awesome, thanks :+1:

**Pull request merged**
