### PR TITLE
Handle multiple matching elements in text assertion

### PR DESCRIPTION
**Pull request by mltsy**
When multiple elements match selector, text assertion was failing

- Added tests
- Fixed assertion

**Update:** Added the same fix for `visible` assertion

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]

**Comment by mltsy** [comment]
I ran into the same problem with the `visible` assertion today, so I figured I'd just throw that fix in here with the other one.  I also changed the assertions to use `$$(selector)` to always get an array, which makes testing a little bit more complex (due to requiring chained stubs), but the library itself is cleaner this way.  Let me know if you'd rather change it back!

**Review by marcodejongh — CHANGES_REQUESTED** [review]
Could you add some simple documentation on how it should be used to the readme?

**Comment by mltsy** [comment]
Well it doesn't change the syntax or anything at all.  It's using the same assertion as for matching a single element - just correctly handles the case now where the selector happens to match multiple elements instead of a single element... any specific documentation you had in mind?

**Comment by mltsy** [comment]
How's that? :)

**Review by marcodejongh — APPROVED** [review]

**Comment by christian-bromann** [comment]
@mltsy there are conflicts, can you please resolve then?

**Comment by mltsy** [comment]
Oops!  Yes I can :)

**Comment by mltsy** [comment]
Fixed :)  I added multiple match handling to the new `value` assertion as well (and `focus` didn't need any changes to work with multiple matches).

**Comment by christian-bromann** [comment]
Still conflicts

**Comment by christian-bromann** [comment]
nevermind, only if you want to rebase

**Review by christian-bromann — APPROVED** [review]

**Comment by mltsy** [comment]
Oh yes, sorry, I did a merge rather than a rebase.  Hopefully you don't mind? (I defaulted to avoiding rewriting history now that the branch has been public and sitting here for 2 months - but I certainly could rebase if you'd prefer @marcodejongh)

**Pull request merged**
