### PR TITLE
Don't use `waitForExist` in visible and count assertions

### PR DESCRIPTION
**Pull request by ghost**
Assertions that an element is not visible are throwing errors when the element exists. Similarly, asserting that the count of elements does not match a given number also throws an error. This is because the `negate` flag is being treated the same as the `reverse` flag for `waitForExist`, causing the assertions to blow up when the element exists.

Note that negating an assertion does not necessarily mean the element should not exist. In the case of `visible`, we could be checking that an element that exists in the DOM is not visible (ex. visbility hidden). Likewise, stating that the count of elements is not equal to a number does not mean that we expect no instance of that element type to exist.

This changes `visible` to use `waitForVisible` instead of `waitForExist` to give the expected behavior when working with wait times (i.e. the client will wait for the element to be visible/not visible as opposed to waiting for it to exist/not exist).

This changes `count` to use `waitUntil` instead of `waitForExist` to give the expected behavior as well (i.e. the client will wait for the element to appear/not appear a certain number of times instead of waiting for it to exist/not exist).

### CODE REVIEW

**Comment by ghost** [comment]
@marcodejongh

**Comment by mltsy** [comment]
Wow, I don't know how I never ran into this problem!  This looks mostly good, but I wonder about calling `elementExists` at all when trying to assert `.not.visible()` ... If an element doesn't exist, it's not visible, so my first thought is to possibly just remove that call if negated.  But currently that call is where the default timeout is implemented, so if we do that, we might have to replace `isVisible` with `waitForVisible` (either negated or not) with the default timeout - which actually... is probably the best/simplest solution in the end!  That's what someone would probably expect to be called when asserting `.visible()` or `.not.visible()` - would you agree?

**Comment by ghost** [comment]
Sounds good! I will update the PR to use `waitForVisible`

**Comment by ghost** [comment]
@mltsy 💇‍♂️ Updated `visible` to use `waitForVisible` instead of `waitForExist`

**Comment by mltsy** [comment]
Awesome!  That looks great.  Well... okay, the `visible` updates look great.  Now that you point that all out, I'm pretty sure the following `count` assertion will still fail when `$('selector')` doesn't exist:

```javascript
expect('selector').not.to.have.count(2);
```

Do you feel up to fixing that in a similar way here, or should we just remove the changes in `count.js` and open a new issue for that?

**Comment by mltsy** [comment]
The problem really is that we can't use `elementExists` or `elementVisible` to implement a wait there... I guess we could use `waitUntil` to wait until the count matches.  But I'm not sure that will give a very informative exception message.  Might be better to just add loop that waits 10ms and checks again until the defaultWaitTime has elapsed (or some such thing) and then return a custom exception message as usual.

**Comment by ghost** [comment]
@mltsy 💇 I updated `count` to use `waitUntil` instead of `waitForExist`

`waitUntil` gives an option to provide the error message that is thrown when the condition is not met, so we can still leverage it without modification in the negated case. For the non-negated case, we can keep an external store for the element count to throw a meaningful error with the actual count (and still be able to use `waitUntil`).

**Comment by mltsy** [comment]
That looks pretty good to me!  (Although, wow, some of those tests are very detailed!  Which means they're going to be brittle, but we can deal with those if and when the implementation changes - for now, very thorough testing!) :wink:  @marcodejongh?

**Comment by mltsy** [comment]
@joshlam - can you update CHANGELOG.md under a new heading for v4.2 to describe the changes you've made?  Other than than, @marcodejongh I think this is ready and probably worth releasing as 4.2, as there are no other bug tickets in currently (other than https://github.com/marcodejongh/chai-webdriverio/issues/19 - which I will take a quick look at I guess, but you could publish 4.2 without that)

**Comment by ghost** [comment]
@mltsy updated the changelog!

**Pull request merged**
